# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonup = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonup.setGeometry(QtCore.QRect(30, 200, 93, 28))
        self.pushButtonup.setObjectName("pushButtonup")
        self.pushButtondown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtondown.setGeometry(QtCore.QRect(30, 250, 93, 28))
        self.pushButtondown.setObjectName("pushButtondown")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 160, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 160, 71, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton0.setGeometry(QtCore.QRect(210, 200, 93, 28))
        self.pushButton0.setObjectName("pushButton0")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(210, 250, 93, 28))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(210, 300, 93, 28))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButtonswitch = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonswitch.setGeometry(QtCore.QRect(10, 10, 131, 41))
        self.pushButtonswitch.setObjectName("pushButtonswitch")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(430, 80, 141, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(590, 80, 201, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.target_tem = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.target_tem.setObjectName("target_tem")
        self.verticalLayout_2.addWidget(self.target_tem)
        self.now_tem = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.now_tem.setObjectName("now_tem")
        self.verticalLayout_2.addWidget(self.now_tem)
        self.wind = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.wind.setObjectName("wind")
        self.verticalLayout_2.addWidget(self.wind)
        self.high_tem = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.high_tem.setObjectName("high_tem")
        self.verticalLayout_2.addWidget(self.high_tem)
        self.low_tem = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.low_tem.setObjectName("low_tem")
        self.verticalLayout_2.addWidget(self.low_tem)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(430, 300, 141, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(590, 300, 201, 161))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.energy = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.energy.setObjectName("energy")
        self.verticalLayout_4.addWidget(self.energy)
        self.fee = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.fee.setObjectName("fee")
        self.verticalLayout_4.addWidget(self.fee)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonup.setText(_translate("MainWindow", "up"))
        self.pushButtondown.setText(_translate("MainWindow", "down"))
        self.label.setText(_translate("MainWindow", "目标温度调节"))
        self.label_2.setText(_translate("MainWindow", "风速调节"))
        self.pushButton0.setText(_translate("MainWindow", "0-无风"))
        self.pushButton1.setText(_translate("MainWindow", "1-微风"))
        self.pushButton2.setText(_translate("MainWindow", "2-中风"))
        self.pushButtonswitch.setText(_translate("MainWindow", "开关"))
        self.label_5.setText(_translate("MainWindow", "目标温度"))
        self.label_4.setText(_translate("MainWindow", "当前温度"))
        self.label_3.setText(_translate("MainWindow", "风速"))
        self.label_6.setText(_translate("MainWindow", "最高温度"))
        self.label_7.setText(_translate("MainWindow", "最低温度"))
        self.target_tem.setText(_translate("MainWindow", "TextLabel"))
        self.now_tem.setText(_translate("MainWindow", "TextLabel"))
        self.wind.setText(_translate("MainWindow", "TextLabel"))
        self.high_tem.setText(_translate("MainWindow", "TextLabel"))
        self.low_tem.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "房间号"))
        self.label_10.setText(_translate("MainWindow", "耗能"))
        self.label_8.setText(_translate("MainWindow", "费用"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.energy.setText(_translate("MainWindow", "TextLabel"))
        self.fee.setText(_translate("MainWindow", "TextLabel"))

